datamodule:
  class_path: _3_data_management._3_2_data_modules.EEG_epochs.EEGEpochsDataModule.EEGEpochsDataModule
  init_args:
    batch_size: 64
    channel_wise_transformations_as_hyphenated_list: no_transformation-delta_band_filtering-theta_band_filtering-alpha_band_filtering-low_beta_band_filtering-high_beta_band_filtering-gamma_band_filtering
    channel_wise_transformations_config_file: SPD_matrices_from_EEG_transformations_config.yaml
    cross_validation_fold_index: 11
    dataloader_num_workers: 5
    dataset_config_file: EEG_epochs_MASS_dataset_EUSIPCO_signals_config.yaml
    obligatory_token_covariance_estimator: cov
    random_seed: 42
    rebalance_training_set_by_oversampling: true
    signal_preprocessing_strategy: z_score_normalization
model:
  class_path: _4_models._4_2_signal_feature_extractor_models.MultichannelIITNetFeatureExtractorPretraining.MultichannelIITNetFeatureExtractorPretraining
  init_args:
    class_labels_list:
    - N3
    - N2
    - N1
    - REM
    - Awake
    dropout_rate: 0.5
    extractor_model:
      class_path: _4_models._4_2_signal_feature_extractor_models.extractor_model.iitnet_feature_extractor.MultichannelIITNetFeatureExtractorModel.MultichannelIITNetFeatureExtractorModel
    features_to_classification_block:
      class_path: _4_models._4_2_signal_feature_extractor_models.features_to_classification_block.pretraining_feature_to_classification_block.MultichannelFeatureExtractorPretrainingBlock.MultichannelFeatureExtractorPretrainingBlock
    learning_rate: 0.00043454244526732995
    loss_function_config_dict:
      name: cross_entropy
    number_of_independent_channels: 7
    number_of_output_features: 30
    number_of_parallel_channels: 8
    optimisation_config_dict:
      optimizer:
        class_path: torch.optim.Adam
        extra_kwargs:
          betas:
          - 0.9
          - 0.999
          eps: 1.0e-07
          weight_decay: 1.0e-05
      scheduler:
        class_path: torch.optim.lr_scheduler.ExponentialLR
        extra_kwargs:
          gamma: 0.94
    output_feature_length: 3
    resnet_num_layers: 50
    signal_length: 7680
