wrapper:
  dataset:
    class_path: _3_data_management._3_2_data_modules.EEG_epochs.datasets.EEGEpochsDataset.EEGEpochsDataset
    init_args:
      eeg_signals:
        - F3
        - F4
        - C3
        - C4
        - T3
        - T4
        - O1
        - O2
      labels:
        - N3
        - N2
        - N1
        - REM
        - Awake
      data_reader_config_file: EEG_epochs_and_corresponding_SPD_matrices_config.yaml