wrapper:
  dataset:
    class_path: _3_data_management._3_2_data_modules.SPD_matrices_from_EEG_signals.datasets.StandardVectorizedSPDFromEEGDataset.StandardVectorizedSPDFromEEGDataset
    init_args:
      eeg_signals:
        - C3-M2
        - F3-M2
        - F4-M1
        - FP1-M2
        - FP2-M1
        - O1-M2
        - O2-M1
      labels:
        - N3
        - N2
        - N1
        - REM
        - Awake
      data_reader_config_file: SPD_matrices_from_EEG_Dreem_config.yaml