class_path: _3_data_management._3_2_data_modules.SPD_matrices_from_EEG_signals.SPDFromEEGDataModule.SPDFromEEGDataModule
init_args:
  dataset_config_file: EEG_epochs_and_corresponding_SPD_matrices_MASS_SS1_dataset_EUSIPCO_signals_config.yaml
  batch_size: 64
  cross_validation_fold_index: 11
  extra_epochs_on_each_side: 10
  signal_preprocessing_strategy: z_score_normalization
  channel_wise_transformations_config_file: SPD_matrices_from_EEG_transformations_config.yaml
  channel_wise_transformations_as_hyphenated_list: no_transformation-delta_band_filtering-theta_band_filtering-alpha_band_filtering-low_beta_band_filtering-high_beta_band_filtering-gamma_band_filtering
  covariance_estimator: cov
  statistic_vectors_for_matrix_augmentation_as_hyphenated_list: ""
  transfer_recording_wise_matrices: true
  rebalance_training_set_by_oversampling: true
  clip_test_set_recordings_by_amount: 24
  dataloader_num_workers: 4
  use_recording_wise_simple_covariances: false
  no_covariances: false
  get_epoch_eeg_signals: true
  random_seed: 42