learning_rate:
  type: loguniform
  args: [1.e-6, 5.e-4]
NESTED:
  - item: name # loss_function_config_dict
    path: loss_function_config_dict
    type: categorical
    args:
      - cross_entropy
      - cross_entropy_with_label_smoothing